// generation/passingChords.js
//
// Post-generation pass that inserts passing chords into a structural chord Melody.
//
// ─── ARCHITECTURE ────────────────────────────────────────────────────────────
//
// Chord generation uses a two-level density split:
//
//   structuralCount = ceil(chordCount / 2)   → generated by MelodyGenerator
//   passingProbability = (chordCount − structuralCount) / structuralCount
//
// passingProbability is the expected number of passing chords per structural gap.
// It can be fractional — the fractional part becomes a probability for inserting
// one extra chord.
//
// Examples (structuralCount = gaps per measure):
//   chordCount=2, structural=1, gaps/meas=1: prob=1.0 → always 1 passing/gap  → total=2/meas ✓
//   chordCount=3, structural=2, gaps/meas=2: prob=0.5 → 50% chance/gap        → expected 3/meas ✓
//   chordCount=4, structural=2, gaps/meas=2: prob=1.0 → always 1 passing/gap  → total=4/meas ✓
//   chordCount=2.5,structural=2,gaps/meas=2: prob=0.25→ 25% chance/gap        → expected 2.5/meas ✓
//
// ─── SNAP GRID ───────────────────────────────────────────────────────────────
//
// Positions are derived by dividing each gap into (insertCount + 1) equal parts,
// then snapping to the nearest grid position. The grid unit matches the normal
// chord generator's `smallestNoteDenom = ts[1]`:
//
//   gridUnit = TICKS_PER_WHOLE / ts[1]
//
// This gives quarter-note slots for 4/4 and 3/4, and 8th-note slots for 6/8 —
// exactly the same resolution the ranked array uses for chord placement.
//
// At variability=0:
//   4/4, chordCount=2, structural=1, gap=[0,48]: rawPos=24 → snap(24,12)=24 (beat 3) ✓
//   3/4, chordCount=2, structural=1, gap=[0,36]: rawPos=18 → snap(18,12)=24 (beat 3) ✓
//   6/8, chordCount=2, structural=1, gap=[0,36]: rawPos=18 → snap(18,6)=18 (beat 3 of 6)✓
//
// ─── SEQUENTIAL CHAINS (insertCount ≥ 2) ─────────────────────────────────────
//
// When insertCount ≥ 2, passing chords form an approach chain built BACKWARDS
// from the target structural chord (each chord resolves forward into the next):
//
//   chain[N−1] = generatePassingChord(…, target=B,          type)
//   chain[N−2] = generatePassingChord(…, target=chain[N−1], type)
//
// Three styles (chromatic suppressed in 'secondary-dominant' mode):
//   Diatonic (40%):        ascending or descending scale walk — IV iii ii I or V vi vii° I
//   Chromatic (30%):       alternates 'secondary-dominant' / 'tritone-sub' (V7/V7 descent)
//   Secondary ii-V (30%): VI/x → ii/x → V7/x (mini ii-V relative to target, may be non-diatonic)
//
// ─── WRAP-AROUND ─────────────────────────────────────────────────────────────
//
// After the last structural chord there is no B. Target = firstChord (first
// structural chord of the melody, representing the start of the next repetition).
// If firstChord is null, the last gap is skipped.
//
// ─── INVARIANTS ──────────────────────────────────────────────────────────────
//
//   • Structural chords are never moved or replaced — only durations are shortened.
//   • insertCount for each gap = floor(prob) + Bernoulli(frac(prob)).
//   • Positions snap to TICKS_PER_WHOLE/ts[1] grid — same as normal chord generator.
//   • Every passing chord carries meta.isPassing = true (set by generatePassingChord).
//   • The returned Melody is sorted by offset — all downstream consumers unchanged.
//
// ─────────────────────────────────────────────────────────────────────────────

import { TICKS_PER_WHOLE } from '../constants/timing.js';
import { generatePassingChord, generateChordOnDegree } from '../theory/chordGenerator.js';
import { getNoteSemitone } from '../theory/noteUtils.js';
import Melody from '../model/Melody.js';

// ─── TYPE SELECTION ──────────────────────────────────────────────────────────

/**
 * Weighted random selection from a table of [type, weight] pairs.
 * Returns a random type proportional to its weight.
 */
function weightedChoice(weightTable) {
    const total = weightTable.reduce((s, [, w]) => s + w, 0);
    let r = Math.random() * total;
    for (const [type, w] of weightTable) {
        r -= w;
        if (r <= 0) return type;
    }
    return weightTable[weightTable.length - 1][0];
}

/**
 * Select a passing chord type for the gap between `currentChord` and `targetChord`,
 * applying exclusion/preference rules from docs/passing-chords-theory.md §6.
 *
 * Same-root exclusion: V7/x has the same root as currentChord when the motion is
 * a rising 4th (I→IV, ii→V, iii→vi, V→I, vi→ii). In that case the secondary
 * dominant barely changes the current chord, so prefer tritone-sub or secondary-dim.
 *
 * Chromatic-clash exclusion: vii°7/x has the same root as currentChord when
 * currentChord.rootPC === (targetPC - 1 + 12) % 12. Prefer other types instead.
 *
 * @param {Chord}  currentChord - The structural chord before the gap (eventA)
 * @param {Chord}  targetChord  - The structural chord after the gap (eventB)
 * @param {string} mode         - 'secondary-dominant' | 'all'
 * @param {boolean} singleChord - true when only one passing chord will be inserted
 * @returns {string} A type key for generatePassingChord
 */
function selectPassingChordType(currentChord, targetChord, mode, singleChord = true) {
    if (mode === 'secondary-dominant') return 'secondary-dominant';

    const currentPC = getNoteSemitone(currentChord.root);
    const targetPC  = getNoteSemitone(targetChord.root);

    // Same-root check: secondary dominant root = (targetPC + 7) % 12.
    // Same-root when that equals currentPC (motion by rising 4th).
    const secDomRootPC = (targetPC + 7) % 12;
    const sameRootAsSecDom = (currentPC === secDomRootPC);

    // Dim-clash check: secondary dim root = (targetPC - 1 + 12) % 12.
    // Clash when that equals currentPC.
    const secDimRootPC = (targetPC - 1 + 12) % 12;
    const sameRootAsSecDim = (currentPC === secDimRootPC);

    // Default weights (§6.1)
    let weights = [
        ['secondary-dominant', 30],
        ['secondary-dim',      20],
        ['tritone-sub',        25],
        ['diatonic',           20],
        ['sus4',                5],
    ];

    if (sameRootAsSecDom) {
        // §6.2: same-root — demote secondary-dominant, promote tritone-sub and dim
        weights = [
            ['secondary-dominant',  5],
            ['secondary-dim',      35],
            ['tritone-sub',        40],
            ['diatonic',           15],
            ['sus4',                5],
        ];
    } else if (sameRootAsSecDim) {
        // §6.3: dim-clash — demote secondary-dim, promote tritone-sub
        weights = [
            ['secondary-dominant', 35],
            ['secondary-dim',       5],
            ['tritone-sub',        40],
            ['diatonic',           15],
            ['sus4',                5],
        ];
    } else if (singleChord) {
        // §6.5: single-chord — slightly elevate sus4 (hover-then-resolve effect most audible in isolation)
        weights = [
            ['secondary-dominant', 28],
            ['secondary-dim',      18],
            ['tritone-sub',        23],
            ['diatonic',           22],
            ['sus4',                9],
        ];
    }

    return weightedChoice(weights);
}

// ─── CHAIN BUILDERS ──────────────────────────────────────────────────────────

/**
 * Diatonic approach chain: stepwise walk through the home scale toward `targetChord`.
 *
 * direction='descending' → approach from above: IV → iii → ii → I
 * direction='ascending'  → approach from below: V  → vi  → vii° → I
 *
 * Built backwards from target so forward-playing order is correct.
 *
 * @param {object} scale
 * @param {Chord}  targetChord
 * @param {number} count
 * @param {'ascending'|'descending'} direction
 * @param {string} complexity
 * @returns {Chord[]} Forward-order chain
 */
function buildDiatonicChain(scale, targetChord, count, direction, complexity) {
    const scaleNotes = scale.notes || [];
    const targetPC = getNoteSemitone(targetChord.root);
    const targetDegIdx = scaleNotes.findIndex(n => getNoteSemitone(n) === targetPC);
    if (targetDegIdx === -1) return [];

    // When building backward from target:
    //   ascending approach means chords below target → build by going down from target
    //   descending approach means chords above target → build by going up from target
    const stepBackward = direction === 'ascending' ? -1 : +1;

    const chain = [];
    let degIdx = targetDegIdx;
    for (let i = 0; i < count; i++) {
        degIdx = ((degIdx + stepBackward + 7) % 7);
        const degree = degIdx + 1; // 1-based
        try {
            const chord = generateChordOnDegree(scale, degree, complexity);
            if (!chord) break;
            chord.meta = { ...chord.meta, isPassing: true };
            chain.push(chord);
        } catch {
            break;
        }
    }
    return chain.reverse(); // reverse to get forward-playing order
}

/**
 * Chromatic approach chain: alternates secondary-dominant and tritone-sub,
 * built backwards from target. Creates a cycle-of-fifths or side-slip descent.
 *
 * @param {object} scale
 * @param {Chord}  targetChord
 * @param {number} count
 * @param {string} complexity
 * @returns {Chord[]} Forward-order chain
 */
function buildChromaticChain(scale, targetChord, count, complexity) {
    const TYPES = ['secondary-dominant', 'tritone-sub'];
    const chain = [];
    let resolveTarget = targetChord;
    for (let i = 0; i < count; i++) {
        const type  = TYPES[i % TYPES.length];
        const chord = generatePassingChord(scale, resolveTarget, type, complexity);
        if (!chord) break;
        chain.push(chord);
        resolveTarget = chord;
    }
    return chain.reverse();
}

/**
 * Secondary ii-V chain: a mini ii-V-I relative to `targetChord` (x), briefly
 * tonicising x via its own ii and V7. May include VI/x for longer chains.
 *
 * count=2: [ii/x, V7/x]
 * count=3: [VI/x, ii/x, V7/x]
 *
 * All chords are built relative to x's root (non-diatonic to home key is expected).
 * Documented in docs/passing-chords-theory.md §5.2.
 *
 * @param {object} scale
 * @param {Chord}  targetChord
 * @param {number} count
 * @param {string} complexity
 * @returns {Chord[]} Forward-order chain
 */
function buildSecondaryIIVChain(scale, targetChord, count, complexity) {
    // Build the chain from innermost outward, then slice to desired count.
    // V7/x is always last, ii/x before it, VI/x (if needed) first.
    const steps = [];

    if (count >= 3) {
        const viChord = generatePassingChord(scale, targetChord, 'iiv-VI', complexity);
        if (viChord) steps.push(viChord);
    }
    if (count >= 2) {
        const iiChord = generatePassingChord(scale, targetChord, 'iiv-ii', complexity);
        if (iiChord) steps.push(iiChord);
    }
    const v7Chord = generatePassingChord(scale, targetChord, 'secondary-dominant', complexity);
    if (v7Chord) steps.push(v7Chord);

    // Return only as many as were successfully built (may be fewer than count)
    return steps;
}

/**
 * Snap a raw tick position to the nearest `gridUnit` boundary, staying strictly
 * inside (gapStart, gapEnd). Returns null if no valid grid position exists.
 *
 * @param {number} rawPos
 * @param {number} gridUnit  - Snap resolution in ticks (TICKS_PER_WHOLE / ts[1])
 * @param {number} gapStart  - exclusive lower bound
 * @param {number} gapEnd    - exclusive upper bound
 */
function snapToGrid(rawPos, gridUnit, gapStart, gapEnd) {
    const snapped = Math.round(rawPos / gridUnit) * gridUnit;
    if (snapped > gapStart && snapped < gapEnd) return snapped;
    // Try adjacent steps if nearest snap fell outside the gap
    for (let delta = 1; delta * gridUnit < (gapEnd - gapStart); delta++) {
        const lo = snapped - delta * gridUnit;
        const hi = snapped + delta * gridUnit;
        if (lo > gapStart && lo < gapEnd) return lo;
        if (hi > gapStart && hi < gapEnd) return hi;
    }
    return null;
}

/**
 * Insert passing chords between structural chord changes in a chord Melody.
 *
 * @param {Melody}     chordMelody        - Structural chord Melody (from MelodyGenerator)
 * @param {object}     scale              - Scale instance
 * @param {number[]}   timeSignature      - [numerator, denominator]
 * @param {string}     complexity         - Chord complexity key, e.g. 'triad'
 * @param {string}     mode               - 'secondary-dominant' | 'all'
 * @param {number}     chordCount         - Total desired chords per measure (UI value).
 *                                         Used to compute passingProbability internally.
 * @param {Chord|null} firstChord         - First structural chord; used for wrap-around gap.
 * @param {number}     rhythmVariability  - 0–100. Controls stochasticity of insertion:
 *                                         0 = deterministic (Math.round of probability),
 *                                         100 = fully stochastic (current random flip behaviour).
 *                                         Intermediate values blend between both modes.
 * @returns {Melody} New Melody with passing chords inserted
 */
export function insertPassingChords(chordMelody, scale, timeSignature, complexity, mode, chordCount, firstChord = null, rhythmVariability = 100) {
    if (!chordMelody || !chordMelody.displayNotes || chordMelody.displayNotes.length === 0) {
        return chordMelody;
    }

    // New balance logic: exactly 1 structural chord per measure (near beat 1),
    // and chordCount-1 passing chords per measure fill the rest.
    // The structural chord is placed at the highest-ranked slot (beat 1) by MelodyGenerator
    // using the rank + 2×distance proximity formula from proximityUtils.findBestSlot.
    // This guarantees each measure always contains exactly one chord from the progression.
    const passingProbability = chordCount - 1; // total passing per structural gap
    // baseInsert: always insert this many per gap; extraProb: chance of one more.
    const baseInsert = Math.floor(passingProbability);
    const extraProb  = passingProbability - baseInsert;

    if (passingProbability <= 0) return chordMelody;

    // Grid unit: same resolution as the normal chord generator (smallestNoteDenom = ts[1]).
    // Quarter notes for 4/4 and 3/4, 8th notes for 6/8, etc.
    const gridUnit = TICKS_PER_WHOLE / timeSignature[1];

    // ── Collect structural chord events ──────────────────────────────────────
    const structural = [];
    for (let i = 0; i < chordMelody.displayNotes.length; i++) {
        const chord    = chordMelody.displayNotes[i];
        const offset   = chordMelody.offsets[i];
        const duration = chordMelody.durations[i];
        if (chord !== null && offset !== null && duration !== null) {
            structural.push({ chord, offset, duration, notes: chordMelody.notes[i] });
        }
    }
    structural.sort((a, b) => a.offset - b.offset);

    // events: mutable copies of structural chords; passing chords appended below
    const events = structural.map(e => ({ ...e }));

    // ── Build gap list ────────────────────────────────────────────────────────
    const gaps = [];
    for (let i = 0; i < structural.length - 1; i++) {
        gaps.push({ eventsIdx: i, targetChord: structural[i + 1].chord, gapEnd: structural[i + 1].offset });
    }
    // Wrap-around: gap after last structural chord resolves to firstChord
    if (firstChord && structural.length > 0) {
        const last = structural[structural.length - 1];
        const wrapEnd = last.offset + last.duration;
        if (wrapEnd > last.offset) {
            gaps.push({ eventsIdx: structural.length - 1, targetChord: firstChord, gapEnd: wrapEnd });
        }
    }

    // ── Fill each gap ─────────────────────────────────────────────────────────
    for (const { eventsIdx, targetChord, gapEnd } of gaps) {
        const eventA   = events[eventsIdx];
        const gapStart = eventA.offset;
        const gapLen   = gapEnd - gapStart;

        if (gapLen <= gridUnit) continue; // gap too small for even one passing chord

        // Decide how many passing chords to insert in this gap.
        // rhythmVariability (0–100) controls the blend between deterministic and stochastic:
        //   0   → Math.round(passingProbability) — always the "expected" count, no randomness
        //   100 → baseInsert + Bernoulli(extraProb) — fully stochastic (original behaviour)
        //   n   → coin-flip: with probability n/100 use stochastic, else use deterministic
        const variabilityFactor = (rhythmVariability || 0) / 100;
        const deterministicCount = Math.round(passingProbability);
        const stochasticCount    = baseInsert + (Math.random() < extraProb ? 1 : 0);
        const insertCount        = Math.random() < variabilityFactor ? stochasticCount : deterministicCount;
        if (insertCount === 0) continue;

        // Evenly-spaced positions within gap, snapped to gridUnit.
        // Divides gap into (insertCount + 1) equal parts; k-th boundary = rawPos.
        const positions = [];
        const step = gapLen / (insertCount + 1);
        for (let k = 1; k <= insertCount; k++) {
            const raw     = gapStart + k * step;
            const snapped = snapToGrid(raw, gridUnit, gapStart, gapEnd);
            if (snapped !== null) positions.push(snapped);
        }
        const uniquePositions = [...new Set(positions)].sort((a, b) => a - b);
        if (uniquePositions.length === 0) continue;

        // ── Generate passing chords ───────────────────────────────────────────
        let passingChords;
        if (uniquePositions.length === 1) {
            // Weighted type selection accounts for same-root and dim-clash exclusions (§6).
            const type = selectPassingChordType(eventA.chord, targetChord, mode, true);
            const chord = generatePassingChord(scale, targetChord, type, complexity);
            passingChords = chord ? [chord] : [];
        } else {
            // Multi-chord chain: pick a style (§7).
            // In secondary-dominant mode only diatonic and secondary-iiv are allowed
            // (tritone-sub and chromatic alternation are suppressed).
            let style;
            if (mode === 'secondary-dominant') {
                style = Math.random() < 0.5 ? 'diatonic' : 'secondary-iiv';
            } else {
                const r = Math.random();
                style = r < 0.40 ? 'diatonic' : r < 0.70 ? 'chromatic' : 'secondary-iiv';
            }

            if (style === 'diatonic') {
                // Ascending or descending stepwise walk — direction chosen once per chain
                const direction = Math.random() < 0.5 ? 'ascending' : 'descending';
                passingChords = buildDiatonicChain(scale, targetChord, uniquePositions.length, direction, complexity);
            } else if (style === 'chromatic') {
                passingChords = buildChromaticChain(scale, targetChord, uniquePositions.length, complexity);
            } else {
                // secondary-iiv: VI/x → ii/x → V7/x
                passingChords = buildSecondaryIIVChain(scale, targetChord, uniquePositions.length, complexity);
            }
        }
        if (passingChords.length === 0) continue;

        // Align chords to positions (chain may be shorter than planned on failure)
        const usedPositions = uniquePositions.slice(uniquePositions.length - passingChords.length);

        // Shorten eventA to end at first passing chord; push passing chord events
        eventA.duration = usedPositions[0] - eventA.offset;
        for (let j = 0; j < passingChords.length; j++) {
            const pOffset   = usedPositions[j];
            const pEnd      = j + 1 < usedPositions.length ? usedPositions[j + 1] : gapEnd;
            events.push({
                chord:    passingChords[j],
                offset:   pOffset,
                duration: pEnd - pOffset,
                notes:    passingChords[j].notes,
            });
        }
    }

    // ── Rebuild Melody ────────────────────────────────────────────────────────
    events.sort((a, b) => a.offset - b.offset);

    return new Melody(
        events.map(e => e.notes),
        events.map(e => e.duration),
        events.map(e => e.offset),
        events.map(e => e.chord),
        events.map(() => null),
    );
}
