export const instrumentOptions = {
    'Acoustic Grand Piano': 'acoustic_grand_piano',
    Harp: 'orchestral_harp',
    'Acoustic Guitar (Nylon)': 'acoustic_guitar_nylon',
    'Acoustic Guitar (Steel)': 'acoustic_guitar_steel',
    'Electric Guitar (Clean)': 'electric_guitar_clean',
    'Electric Bass (Picked)': 'electric_bass_pick',
    'Synth Bass': 'synth_bass_1',
    'Slap Bass': 'slap_bass_2',
    Violin: 'violin',
    'String Ensemble': 'string_ensemble_1',
    Trumpet: 'trumpet',
    Saxophone: 'tenor_sax',
    Flute: 'flute',
    Marimba: 'marimba',
    'Voice Oohs': 'voice_oohs',
    'Standard Drums (GM)': 'standard',
    'Electronic Drums (GM)': 'electronic',
    'Jazz Drums (GM)': 'jazz',
    '808 (Vintage)': 'TR-808',
    'RZ-1 (Vintage)': 'Casio-RZ1',
    'LM-2 (Vintage)': 'LM-2',
    'MFB-512 (Vintage)': 'MFB-512',
    'CR-8000 (Vintage)': 'Roland CR-8000',
};
